[build]
  publish = "."

[[redirects]]
  from = "/go/:slot"
  to = "/go/index.html?slot=:slot"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
